phase: local

server:
  port: 8080

spring:
  jpa:
    show-sql: true
    open-in-view: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57InnoDBDialect
      hibernate.format_sql: true
      hibernate.enable_lazy_load_no_trans: true
      hibernate.connection.handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
      hibernate.physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      hibernate.implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    url: jdbc:mysql://localhost:3306/holycard?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver